/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


/**
 *
 * @author bernardo_o_silva
 */
public class Interface02 extends javax.swing.JFrame {

    /**
     * Creates new form Interface02
     */
    public Interface02() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textoSuperior = new javax.swing.JLabel();
        campoInput = new javax.swing.JTextField();
        botao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textoSuperior.setFont(new java.awt.Font("Engravers MT", 1, 18)); // NOI18N
        textoSuperior.setForeground(new java.awt.Color(0, 0, 0));
        textoSuperior.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoSuperior.setText("TELA INICIAL");

        campoInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoInputActionPerformed(evt);
            }
        });

        botao.setBackground(new java.awt.Color(204, 255, 204));
        botao.setFont(new java.awt.Font("Century Schoolbook", 0, 11)); // NOI18N
        botao.setForeground(new java.awt.Color(51, 255, 51));
        botao.setText("CLIQUE AQUI");
        botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoActionPerformed(evt);
            }
        });
        botao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botaoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(textoSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                    .addComponent(campoInput)
                    .addComponent(botao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(textoSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(campoInput, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botao, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoInputActionPerformed

    private void botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoActionPerformed
        String texto = campoInput.getText();
        textoSuperior.setText(texto);
    }//GEN-LAST:event_botaoActionPerformed

    private void botaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botaoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao;
    private javax.swing.JTextField campoInput;
    private javax.swing.JLabel textoSuperior;
    // End of variables declaration//GEN-END:variables
}
